estagio/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'estagio'
urlpatterns = [
    path('', views.index, name= 'index'),
    # path('vagas/', views.vagas, name='vagas'),
    path('vagas/', views.listar_instituicoes, name='vagas'),
    path('vagas/<id>/', views.listar_cursos_e_locais, name='listar_cursos_e_locais'),
    
    path('getLocais/<id>/', views.getLocais, name='get_locais'),
    path('getVagas/<id>/', views.getVagas, name='get_vagas'),
    path('getCursos/<id>/', views.getCursos, name='get_cursos'),
    
    path('area-do-estudante/', views.area_do_estudante, name='area_do_estudante'),
    path('area-da-universidade/', views.area_da_universidade, name='area_da_universidade'),
    path('area-do-estudante/processo/156f165f1<id>4f654f', views.processo_da_vaga, name='processo_da_vaga'),
    path('area-do-estudante/processo/156f165f1<id>4f654f/anexar-tce/', views.anexar_tce, name='anexar_tce'),
    path('area-do-estudante/processo/156f165f1<id>4f654f/vizualiar-tce/', views.visualizar_tce, name='visualizar_tce'),
    
    path('adm/', views.adm, name='adm'),
    path('vagas/cadastrar/', views.cadastro_vaga, name='cadastro_vaga'),
    path('vagas/<id>/<id_curso>/canditar-se/', views.candidatar_se_vaga, name='candidatar_se_vaga'),
    path('candidato/', views.listar_candidato, name='candidato'),
    path('estagiario/', views.listar_estagiario, name='estagiario'),
    path('adm/processo/156f165f1<id>4f654f/', views.adm_processo_da_vaga, name='adm_processo_da_vaga'),
    path('candidato/<id>/editar/', views.editar_estudante, name='editar_candidato'),
    path('candidato/<id>/editar/gerar-processo', views.editar_estudante_processo, name='editar_candidato_processo'),
    path('universidade/', views.listar_universidade, name='listar_universidade'),
    path('universidade/cadastrar_universidade/', views.cadastrar_universidade, name="cadastrar_universidade"),
    path('universidade/<id>/cadastrar_curso', views.cadastrar_curso, name='cadastrar_curso'),
    path('universidade/<id>/curso', views.listar_curso, name='curso'),
    path('universidade/<id>/editar', views.editar_curso, name='editar_curso'),
    path('supervisor/', views.listar_supervisor, name='listar_supervisor'),
    path('supervisor/cadastrar_supervisor', views.cadastrar_supervisor, name='cadastrar_supervisor'),
    path('supervisor/<id>/editar', views.editar_supervisor, name='editar_supervisor'),
    path('secretaria/', views.listar_secretaria, name='listar_secretaria'),
    path('secretaria/<id>/locais/', views.listar_secretaria_locais, name='listar_secretaria_locais'),
    path('secretaria/cadastrar_secretaria', views.cadastrar_secretaria, name='cadastrar_secretaria'),
    path('secretaria/<id>/cadastrar_local', views.cadastrar_local, name='cadastrar_local'),
    path('secretaria/<id>/locais/detalhes/<id_local>', views.locais_detalhes, name="listar_detalhes_do_local"),
    path('secretaria/<id>/locais/detalhes/<id_local>/adicionar-ou-remover', views.locais_detalhes_adicionar_ou_remover, name="listar_detalhes_do_local_add_ou_rmv"),    
    path('adm/vagas/', views.listar_vagas, name='listar_vagas'),
    path('adm/vagas/cadastrar', views.cadastrar_vagas, name='cadastrar_vagas'),
    path('adm/vagas/<id>/editar', views.editar_vagas, name='editar_vagas'),
    path('get_courses_by_university/<university_id>', views.get_courses_by_university, name='get_courses_by_university'),

]

estagio/templates/nav_estagio.html
<div id="navegacao" class="container">
    <div class="row">
      <div class="col d-flex justify-content-center flex-wrap">
        <a href="{% url 'estagio:index' %}" class="">
          <div class="d-flex flex-column align-items-center">
            <div
              id="s-index"
              class="s-nav rounded-circle {% block index %}{% endblock %}"
            ></div>
            <p class="text-dark">Início</p>
          </div>
        </a>
        <a href="{% url 'estagio:vagas' %}" class="">
          <div class="d-flex flex-column align-items-center">
            <div id="s-vagas" class="s-nav rounded-circle"></div>
            <p class="text-dark text-center">Vagas de <br>estágio</p>
          </div>
        </a> 
        <a href="{% url 'estagio:area_do_estudante' %}" class="">
          <div class="d-flex flex-column align-items-center">
            <div id="s-estudante" class="s-nav rounded-circle destaque"></div>
            <p class="text-dark  text-center">Área do <br>estudante</p>
          </div>
        </a>
        <a href="{% url 'estagio:area_da_universidade' %}" class="">
          <div class="d-flex flex-column align-items-center">
            <div id="s-universidade" class="s-nav rounded-circle destaque"></div>
            <p class="text-dark  text-center">Área da <br>instituição</p>
          </div>
        </a>
        {% if request.user.is_staff %}
        <a href="{% url 'estagio:adm' %}" class="">
          <div class="d-flex flex-column align-items-center">
            <div id="s-admin" class="s-nav rounded-circle destaque"></div>
            <p class="text-dark">Admin</p>
          </div>
        </a>
        {% endif %}
      </div>
    </div>
  </div>
  <style>
    #s-index {
      margin-right: 1rem !important;
      background-color: white !important;
      background-image: url(/static/images/icones/estagio_.png);
      background-size: contain;
    }
    #s-vagas {
      margin-right: 1rem !important;
      background-color: white !important;
      background-image: url(/static/images/icones/estagio_vagas.png);
      background-size: contain;
    }
    #s-instituicao {
      margin-right: 1rem !important;
      background-color: white !important;
      background-image: url(/static/images/icones/estagio_instituicao.png);
      background-size: contain;
    }
    #s-candidatos {
      margin-right: 1rem !important;
      background-color: white !important;
      background-image: url(/static/images/icones/estagio_candidatos.png);
      background-size: contain;
    }
    #s-estagiarios {
      margin-right: 1rem !important;
      background-color: white !important;
      background-image: url(/static/images/icones/estagio_estagiarios.png);
      background-size: contain;
    }
    #s-universidade {
      margin-right: 1rem !important;
      background-color: white !important;
      background-image: url(/static/images/icones/estagio_universidade.png);
      background-size: contain;
    }
    #s-supervisor {
      margin-right: 1rem !important;
      background-color: white !important;
      background-image: url(/static/images/icones/estagio_supervisor.png);
      background-size: contain;
    }
    #s-secretaria {
      margin-right: 1rem !important;
      background-color: white !important;
      background-image: url(/static/images/icones/estagio_secretaria.png);
      background-size: contain;
    }
    #s-estudante {
      margin-right: 1rem !important;
      background-color: white !important;
      background-image: url(/static/images/icones/curso_admin.png);
      background-size: contain;
    }
    #s-universidade {
      margin-right: 1rem !important;
      background-color: white !important;
      background-image: url(/static/images/icones/estagio_area_universidade.png);
      background-size: contain;
    }
    #s-admin {
      margin-right: 1rem !important;
      background-color: white !important;
      /* background-image: url(/static/images/icones/curso_admin.png); */
      background-size: contain;
    }
  </style>
  

estagio/templates/slide_estagio.html
<div id="slideContainer" class="border" style="border-radius: 30px;">
    <div class="slide active" style="box-shadow: 0px 10px 15px -3px rgba(0, 0, 0, 0.1); border-radius: 30px;">
      <div class="row">
        <div class="banner_destaque d-flex flex-column flex-xl-row bg-white img-txt">
          <div class="img-destaque">
            <img class="banner_img_destaque w-100 h-100" src="/static/images/banner_estagio.png">
          </div>
          <!-- <div style="max-width: 400px;" class="m-auto text-destaque pb-0 d-flex flex-column">
            <h3 class="mb-4">BEM-VINDO</h3>
            <p>
              O estágio é um elo vital entre a educação e a carreira, moldando habilidades práticas e conhecimentos específicos. Ele fornece pontes entre teoria e aplicação, impulsionando profissionais a contribuir de forma eficaz para nossa sociedade em constante evolução.
            </p>
            <span  id="servicos"></span>
          </div> -->
        </div>
      </div>
    </div>
  </div>
  <script>
    // const slides = document.querySelectorAll('.slide');
    // let currentSlide = 0;
  
    // function showSlide(slideIndex) {
    //   if (slideIndex >= slides.length) {
    //     slideIndex = 0;
    //   } else if (slideIndex < 0) {
    //     slideIndex = slides.length - 1;
    //   }
  
    //   for (let i = 0; i < slides.length; i++) {
    //     slides[i].classList.remove('active');
    //   }
  
    //   slides[slideIndex].classList.add('active');
    //   currentSlide = slideIndex;
    // }
  
    // function nextSlide() {
    //   showSlide(currentSlide + 1);
    // }
  
    // function previousSlide() {
    //   showSlide(currentSlide - 1);
    // }
      
    // document.getElementById('slideContainer').addEventListener('click', function(e) {
    //   if (e.target.classList.contains('next')) {
    //     nextSlide();
    //   } else if (e.target.classList.contains('previous')) {
    //     previousSlide();
    //   }
    // });
      
    // setInterval(nextSlide, 9000);
  </script>