estagio/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'estagio'
urlpatterns = [
    path('', views.index, name= 'index'),
    # path('vagas/', views.vagas, name='vagas'),
    path('vagas/', views.listar_instituicoes, name='vagas'),
    path('vagas/<id>/', views.listar_cursos_e_locais, name='listar_cursos_e_locais'),
    
    path('getLocais/<id>/', views.getLocais, name='get_locais'),
    path('getVagas/<id>/', views.getVagas, name='get_vagas'),
    path('getCursos/<id>/', views.getCursos, name='get_cursos'),
    
    path('area-do-estudante/', views.area_do_estudante, name='area_do_estudante'),
    path('area-da-universidade/', views.area_da_universidade, name='area_da_universidade'),
    path('area-do-estudante/processo/156f165f1<id>4f654f', views.processo_da_vaga, name='processo_da_vaga'),
    path('area-do-estudante/processo/156f165f1<id>4f654f/anexar-tce/', views.anexar_tce, name='anexar_tce'),
    path('area-do-estudante/processo/156f165f1<id>4f654f/vizualiar-tce/', views.visualizar_tce, name='visualizar_tce'),
    
    path('adm/', views.adm, name='adm'),
    path('vagas/cadastrar/', views.cadastro_vaga, name='cadastro_vaga'),
    path('vagas/<id>/<id_curso>/canditar-se/', views.candidatar_se_vaga, name='candidatar_se_vaga'),
    path('candidato/', views.listar_candidato, name='candidato'),
    path('estagiario/', views.listar_estagiario, name='estagiario'),
    path('adm/processo/156f165f1<id>4f654f/', views.adm_processo_da_vaga, name='adm_processo_da_vaga'),
    path('candidato/<id>/editar/', views.editar_estudante, name='editar_candidato'),
    path('candidato/<id>/editar/gerar-processo', views.editar_estudante_processo, name='editar_candidato_processo'),
    path('universidade/', views.listar_universidade, name='listar_universidade'),
    path('universidade/cadastrar_universidade/', views.cadastrar_universidade, name="cadastrar_universidade"),
    path('universidade/<id>/cadastrar_curso', views.cadastrar_curso, name='cadastrar_curso'),
    path('universidade/<id>/curso', views.listar_curso, name='curso'),
    path('universidade/<id>/editar', views.editar_curso, name='editar_curso'),
    path('supervisor/', views.listar_supervisor, name='listar_supervisor'),
    path('supervisor/cadastrar_supervisor', views.cadastrar_supervisor, name='cadastrar_supervisor'),
    path('supervisor/<id>/editar', views.editar_supervisor, name='editar_supervisor'),
    path('secretaria/', views.listar_secretaria, name='listar_secretaria'),
    path('secretaria/<id>/locais/', views.listar_secretaria_locais, name='listar_secretaria_locais'),
    path('secretaria/cadastrar_secretaria', views.cadastrar_secretaria, name='cadastrar_secretaria'),
    path('secretaria/<id>/cadastrar_local', views.cadastrar_local, name='cadastrar_local'),
    path('secretaria/<id>/locais/detalhes/<id_local>', views.locais_detalhes, name="listar_detalhes_do_local"),
    path('secretaria/<id>/locais/detalhes/<id_local>/adicionar-ou-remover', views.locais_detalhes_adicionar_ou_remover, name="listar_detalhes_do_local_add_ou_rmv"),    
    path('adm/vagas/', views.listar_vagas, name='listar_vagas'),
    path('adm/vagas/cadastrar', views.cadastrar_vagas, name='cadastrar_vagas'),
    path('adm/vagas/<id>/editar', views.editar_vagas, name='editar_vagas'),
    path('get_courses_by_university/<university_id>', views.get_courses_by_university, name='get_courses_by_university'),

]

estagio/models.py
import random
import string
from django.db import models
from autenticacao.models import Pessoa
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import FileExtensionValidator


class Universidade(models.Model):    
    nome = models.CharField(max_length=100, verbose_name="Nome da instituição")
    nome_responsavel = models.CharField(max_length=150, verbose_name="Nome do responsável de estágio da instituição")
    contato = models.CharField(max_length=50, verbose_name="Contato do responsável de estágio da instituição")
    logo = models.ImageField(upload_to = 'estagio/media/logo_universidade/', null=True, blank=True)
    dt_inicio_do_termo = models.DateField(null=True, blank=True)
    dt_vencimento_do_termo = models.DateField(null=True, blank=True)
    data_inclusao = models.DateTimeField(auto_now_add=True, editable=False, blank=True)
    ativa = models.BooleanField(default=True)
    def __str__(self):
         return '%s' % (self.nome)

class Responsavel_Universidade(models.Model):
    universidade = models.ForeignKey(Universidade, on_delete=models.CASCADE)
    pessoa = models.ForeignKey(Pessoa, on_delete=models.CASCADE)
    cargo = models.CharField(max_length=20, default='Cargo do Responsável')
    email_institucional = models.EmailField()
    telefone_institucional = models.CharField(max_length=15, verbose_name='Telefone', null=True)

    def __str__(self):
         return '%s - %s' % (self.pessoa.nome, self.universidade.nome)
    
class Curso(models.Model):
    nome = models.CharField(max_length=50, verbose_name="Nome do curso")
    data_inclusao = models.DateTimeField(auto_now_add=True, editable=False, blank=True)
    universidade = models.ForeignKey(Universidade, on_delete= models.CASCADE)
   
    def __str__(self):
         return '%s - %s' % (self.nome, self.universidade.nome)
   
class Secretaria(models.Model):
    nome = models.CharField(max_length=100, verbose_name="Nome da secretaria")    
    telefone = models.CharField(max_length=15, verbose_name='Telefone da secretaria', null=True)
    data_inclusao = models.DateTimeField(auto_now_add=True, editable=False, blank=True)
    
    def __str__(self):
        return self.nome

class Locais_de_Estagio(models.Model):
    secretaria =  models.ForeignKey(Secretaria, on_delete=models.CASCADE)
    local = models.CharField(max_length=100, verbose_name="Nome do local")
    bairro = models.CharField(max_length=100, verbose_name="Bairro")
    telefone_responsavel = models.CharField(max_length=15, verbose_name='Telefone do responsável do local', null=True)
    telefone_local = models.CharField(max_length=15, verbose_name='Telefone do local', null=True)    
    quantidade_maxima = models.IntegerField()
    cursos = models.ManyToManyField(Curso)
    def __str__(self):
        return '%s - %s' % (self.local, self.local)

class Vagas(models.Model):
    nome = models.CharField(max_length=50, verbose_name="Nome vagas")
    descricao = models.TextField(blank=True, null=True)
    quantidade_de_vagas = models.IntegerField(verbose_name="Quantidade de vagas")
    data_inclusao = models.DateTimeField(auto_now_add=True, editable=False, blank=True)
    img = models.ImageField(upload_to = 'estagio/media/banner_vagas/', null=True)
    img2 = models.ImageField(upload_to = 'estagio/media/banner_vagas/', null=True)
    secretaria = models.ManyToManyField(Secretaria)
    curso = models.ManyToManyField(Curso)
    locais = models.ManyToManyField(Locais_de_Estagio)
    quantidade_maxima = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.nome
    
class Supervisor(models.Model):
    pessoa = models.ForeignKey(Pessoa, on_delete=models.CASCADE, null=True, blank=True)
    nome = models.CharField(max_length=200, verbose_name="Nome supervisor")
    data_inclusao = models.DateTimeField(auto_now_add=True, editable=False, blank=True)
    secretaria = models.ForeignKey(Secretaria, on_delete= models.CASCADE)
    n_vagas = models.IntegerField(verbose_name="Número de vagas")
    email = models.EmailField(verbose_name="Email", null=True, blank=True)
    celular =models.CharField(max_length=15, verbose_name="Celular", null=True, blank=True)
    
    def __str__(self):
        return self.nome

class Vaga_Supervisor(models.Model): 
    pessoa = models.ForeignKey(Pessoa, on_delete=models.CASCADE, null=True, blank=True)
    vaga = models.ForeignKey(Vagas, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.vaga     + ' - ' + self.pessoa

class Estudante(models.Model):
    pessoa = models.ForeignKey(Pessoa, related_name='aluno_pessoa', on_delete=models.PROTECT)
    matricula = models.CharField(max_length=50, verbose_name= "Sua matricula")
    data_inclusao = models.DateTimeField(auto_now_add=True, editable=False, blank=True)
    universidade = models.ForeignKey(Universidade, on_delete=models.RESTRICT, verbose_name='Sua universidade atual')
    curso = models.ForeignKey(Curso, on_delete=models.RESTRICT, blank=True, null=True, verbose_name='Seu curso')
    
    def __str__(self):
        return self.pessoa.nome
    
class Estudante_Vaga(models.Model):
    STATUS_CHOICES = (
        ('0', 'Candidato'),
        ('1', 'Estagiando'),
        ('2', 'Estágio concluído'),
        ('3', 'Candidatura cancelada')
    )
    universidade = models.ForeignKey(Universidade, on_delete=models.RESTRICT, blank=True, null=True)
    matricula = models.CharField(max_length=50, verbose_name= "Sua matricula", blank=True, null=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, verbose_name='Status', default=0)
    data_inclusao = models.DateTimeField(auto_now_add=True, editable=False, blank=True)        
    # vaga = models.ForeignKey(Vagas, on_delete=models.RESTRICT)
    supervisor = models.ForeignKey(Supervisor, on_delete=models.RESTRICT, blank=True, null=True)
    estudante = models.ForeignKey(Estudante, on_delete=models.RESTRICT, blank=True, null=True)
    local_do_estagio_de_pretensao = models.ForeignKey(Locais_de_Estagio, related_name='pretensao', on_delete=models.RESTRICT, blank=True, null=True)
    local_do_estagio = models.ForeignKey(Locais_de_Estagio, on_delete=models.RESTRICT, blank=True, null=True)
    data_inicio = models.DateField(verbose_name= "Data inicio", blank=True, null=True)
    data_fim = models.DateField(verbose_name="Data termino", blank=True, null=True)
    TCE = models.FileField(upload_to='TCE', verbose_name='Termo de Compromisso de Estágio', null=True, blank=True, validators=[FileExtensionValidator(['pdf'])])

    def __str__(self):
        return self.estudante.pessoa.nome
    
class Processo(models.Model):

    n_processo = models.CharField(max_length=8, verbose_name='Número do processo', null=True)  
    estudante_vaga = models.ForeignKey(Estudante_Vaga, on_delete=models.CASCADE)
    data_inclusao = models.DateTimeField(auto_now_add=True, editable=False, blank=True)
    
@receiver(post_save, sender=Processo)
def generate_process_number(sender, instance, created, **kwargs):
    if created and not instance.n_processo:  # Verifica se o objeto foi criado recentemente e se o número do processo já existe
        random_part = ''.join(random.choices(string.digits, k=5))
        print('ID:', instance.id)
        n_processo='{}{}'.format(random_part, instance.id)
        aux=len(n_processo)
        if aux>8:
            while aux>8:
                n_processo = n_processo[1:]
                aux=len(n_processo)
                print(n_processo)
        instance.n_processo='{:8}'.format(n_processo.zfill(8))
        instance.save()

class Historico_Processo(models.Model):
    STATUS_CHOICES = (
        ('0', 'Aguardando liberação de vaga'),
        ('1', 'Lista de espera'),
        ('2', 'Aguardando reenvio do TCE'),
        ('3', 'Aguardando termo assinado pelas partes'),
        ('4', 'Processo de seleção concluída'),
        ('5', 'Estágio concluído'),
        ('6', 'Candidatura cancelada')
    )
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, verbose_name='Status', default=0)
    processo=models.ForeignKey(Processo, on_delete=models.CASCADE, null=True)
    data_inclusao = models.DateTimeField(auto_now_add=True, editable=False)
    mensagem=models.TextField(blank=True)

estagio/templates/estagio/adm_processo_da_vaga.html
{% extends 'template.html' %}
{% load static %}
{% block nav %}
{% include 'nav_estagio.html' %}
{% endblock %}
{% block css %} {% endblock %}
{% block main %}

    <div class="d-flex flex-wrap">        
      <h2 id="go">Processo nº {{processo.n_processo}}</h2>   
      {% if TCE %}
      <a target="_blank" class="btn btn-success ms-auto me-2 my-auto" href="{{TCE}}">
       <i class="fa-solid fa-file-pdf me-2"></i>TCE
      </a>    
      {% else %}
      <button target="_blank" class="btn btn-success ms-auto me-2 my-auto" disabled>
        <i class="fa-solid fa-file-pdf me-2"></i>TCE
      </button>    
      {% endif %}
      <a class="btn btn-primary my-auto" href="{% url 'estagio:editar_candidato' id %}">
        <i class="fa-solid fa-paperclip me-2"></i>Atualizar processo
      </a>  
      <a class="btn btn-secondary ms-2 my-auto" href="{{back_to}}">
        <i class="fa-solid fa-backward-step me-2"></i>Voltar
      </a>       
    </div>
    <div class="row">
      <div class="col pt-3 pb-4">
          <div class="table-responsive pt-4 border" style="background-color: white; border-radius: 30px; padding: 20px;">
              <h2>Dados do Candidato</h2>
              
              <table class="table">
                  <tr>
                      <th>Nome</th>
                      <td>{{ estudante.pessoa.nome }}</td>
                  </tr>
                  <tr>
                      <th>Email</th>
                      <td>{{ estudante.pessoa.email }}</td>
                  </tr>
                  <tr>
                      <th>CPF</th>
                      <td>{{ estudante.pessoa.cpf }}</td>
                  </tr>
                  <tr>
                      <th>Telefone</th>
                      <td>{{ estudante.pessoa.telefone }}</td>
                  </tr>
                  <tr>
                      <th>Data de Nascimento</th>
                      <td>{{ estudante.pessoa.dt_nascimento }}</td>
                  </tr>
                  <tr>
                      <th>Bairro</th>
                      <td>{{ estudante.pessoa.bairro }}</td>
                  </tr>
                  <!-- Adicione mais campos conforme necessário -->
                  <tr>
                      <th>Matrícula</th>
                      <td>{{ estudante.matricula }}</td>
                  </tr>
                  <tr>
                      <th>Universidade</th>
                      <td>{{ estudante.universidade.nome }}</td>
                  </tr>
                  <tr>
                      <th>Curso</th>
                      <td>{{ estudante.curso.nome }}</td>
                  </tr>
              </table>
              
          </div>
      </div>
  </div>
  
    <div class="row ">
      <div class="col pt-3 pb-4">
       <div class="table-responsive pt-4 border" style="background-color: white; border-radius: 30px; padding: 20px;">             
        <table class="table table-borderless ">
          <thead>
            <tr>
              <th>Dt. de processo</th>
              <th>Status</th>
              <th>Mensagem</th>
            </tr>
          </thead>
          <tbody>
          {% for h in historico %}          
            <tr class="border-top">
              {% if forloop.first %}
              <td style="background-color: rgba(255, 210, 127, 0.356);"><strong>{{h.data_inclusao}} </strong></td>
              <td style="background-color: rgba(255, 210, 127, 0.356);"><strong>{{h.get_status_display}}</strong></td>
              <td style="background-color: rgba(255, 210, 127, 0.356);"><i><strong>{{h.mensagem}}</strong></i></td>
              {% else %}
              <td>{{h.data_inclusao}}</td>
              <td>{{h.get_status_display}}</td>
              <td><i>{{h.mensagem}}</i></td>
              {% endif %}              
            </tr>            
          {% endfor %}
          </tbody>
        </table>
       </div>
      </div>
    </div>

    

{% endblock %}
{% block footer %}
{% include 'desenvolve_nf/instagram.html' %}
{% endblock %}

estagio/templates/estagio/area_da_universidade.html
{% extends 'template.html' %}
{% load static %}
{% block nav %}
{% include 'nav_estagio.html' %}
{% endblock %}
{% block css %} {% endblock %}
{% block main %}

    <div class="d-flex flex-wrap">        
      <h2 id="go">Área da Instituição</h2>
      <div id="cabecalho" class="ms-auto input-group" style="max-width: 300px ;">          
        <input style="border-radius: 30px !important; padding-right: 35px;" type="search" name="search" id="search"
            class="form-control mb-auto">
        <i class="fa-solid fa-magnifying-glass"
            style="position: absolute; right: 0; margin: 10px 10px auto auto;"></i>
      </div>
    </div>
    <div class="row ">
      <div class="col pt-3 pb-4">
       <div class="table-responsive pt-4 border" style="background-color: white; border-radius: 30px; padding: 20px;">
        {% if estudante %}
        <table class="table table-borderless">
          <thead>
            <tr>
              <th>Universidade</th>
              <th>Contato</th>
              <th>Outras informações</th>
              <th>Vencimento do termo</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="">
                <strong><i>{{estudante.universidade}}</i></strong>
              </td>     
              <td></td>     
              <td></td>
              <td class="">
                <strong>{{estudante.dt_vencimento_do_termo}}</strong>
              </td>          
            </tr>
            <!-- <tr>
              <td>
                {{estudante.}}
              </td>
            </tr> -->
          </tbody>
        </table>
        {% else %}
        <p class="text-center py-5"><i class="text-secondary">Você não se candidatou a nenhuma vaga ainda.</i></p>
        {% endif %}
       </div>
        <!-- <p class="text-secondary"><i>Conheça as vagas de nível tecnico esuperior ofertados pela Prefeitura de Nova Friburgo e suas respectivas instituições!</i></p> -->
      </div>
    </div>
    <div class="row">
      <div class="col">
        <h3>Acompanhamento de vagas</h3>       
      </div>
    </div>
    <div class="row">
      <div class="col">
        <div class="pt-4 border table-responsive" style="background-color: white; border-radius: 30px; padding: 20px;">
          {% if estudante_vagas %}
          <table class="table table-borderless">
            <thead>
                <tr>
                  <th>Estudante</th>
                  
                    <th class="pe-5">Vaga de Estágio</th>                  
                    <th class="pe-5">Secretária</th>                  
                    <th class="pe-5">Local</th>  
                    
                    <th class="pe-5 text-center">Dt. de Solicitação</th>                      
                    <th>Processo</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {% for i in estudante_vagas %}
                <tr>
                  <td>
                    {{i.estudante}}   
                  </td>                 
                  <td class="pe-5">{{i.vaga.nome}}</td>                          
                 
                  <td class="pe-5">
                      {% if i.local_do_estagio.secretaria %}
                      {{i.local_do_estagio.secretaria}}
                      {% else %}
                      <i class="text-secondary">Não definido.</i>
                      {% endif %}
                  </td>                  
                  <td class="pe-5">
                        {% if i.local_do_estagio.local %}
                        {{i.local_do_estagio.local}}
                        {% else %}
                        <i class="text-secondary">Não definido.</i>
                        {% endif %}
                  </td>                                     
                  <td class="pe-5 text-center">{{i.estudante.data_inclusao|date:"d/m/y"}}</td>                                    
                  <td>
                    <a href="{% url 'estagio:processo_da_vaga' i.id %}">Visualizar</a>
                  </td> 
                  <td>
                    {{i.get_status_display}}   
                  </td>
                </tr>
                {% endfor %}                
            </tbody>
        </table>
        {% else %}
        <p class="text-center py-5"><i class="text-secondary">Você não se candidatou a nenhuma vaga ainda.</i></p>
        {% endif %}
        </div>
      </div>
    </div>
    <script>
      document.getElementById('s-universidade').classList.add('s-nav-active');
    </script>
{% endblock %}
{% block footer %}
{% include 'desenvolve_nf/instagram.html' %}
{% endblock %}

estagio/templates/estagio/cadastrar_secretaria.html
{% extends 'template.html' %}
{% load bootstrap5 %}
{% load static %}
{% block nav %}
{% include 'nav_estagio.html' %}
{% endblock %}
{% block css %} {% endblock %}
{% block main %}
        <div class="row">
            <div class="col d-flex">
                <a href="{% url 'estagio:listar_secretaria' %}" class="ms-auto btn btn-primary"><i class="fa-solid fa-backward-step me-2"></i>Voltar</a> 
            </div>
        </div>
        <div class="row">
            <div class="col">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form forms %}
                    <div class="row">
                        <div class="col">
                            <button type="submit">
                                Enviar
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
{% endblock %}
{% block footer %}
{% include 'desenvolve_nf/instagram.html' %}
{% endblock %}

estagio/templates/estagio/getCursos.html
<option value="" selected>---------</option>   
{% for curso in cursos %}
<option value="{{curso.id}}">{{curso.nome}}</option>   
{% endfor %}

estagio/templates/estagio/listar_candidatos.html
{% extends 'template.html' %}
{% load static %}
{% block nav %}
{% include 'nav_estagio.html' %}
{% endblock %}
{% block css %} {% endblock %}
{% block main %}
<style>
    #filtros{
      display: none;
    }
  </style>
<div class="row mb-3">
    <div class="col d-flex">       
        <div class="m-auto py-0 w-100">           
          <div class="cursos-text mx-2 d-flex w-100">
            <h2 class="my-auto">Listar {{subtitulo}} <span class="text-secondary">(Total: {{total}})</span></h2>                        
            <a onclick="showFiltros()" class="ms-auto mt-2 btn btn-dark mb-2">
                <i class="fa-solid fa-filter"></i>
            </a>              
            <a href="{% url 'estagio:adm' %}" class="ms-2 mt-2 me-3 btn btn-primary mb-2">
                <i class="fa-solid fa-backward-step me-2"></i>Voltar
            </a>    
          </div>            
      </div>
    </div>
  </div>
  <div class="w-100 ">                          
    <div id="filtros" class="border py-2 px-4 mt-3 pb-4 pt-3 bg-light" style="border-radius: 12px;">
      <form method="POST" class="d-flex flex-column">        
        <h4>Filtros de busca</h4>                                            
        <div class="d-flex">
          {% csrf_token %}
          <div class="d-flex flex-column">
            <label for="protocolo">Nome do aluno:</label>
            <input name="protocolo" type="text" class="form-control" style="width: 250px;  border-radius: 8px !important;">
          </div>   
                                                                       
          <div class="d-flex flex-column ms-1">
            <label for="status">Universidade:</label>
            <input type="text" name="bairro" class="form-control" style="border-radius: 8px !important;">
          </div>
          <div class="d-flex flex-column ms-1">
            <label for="status">Curso:</label>
            <input type="text" name="rua" class="form-control" style="width: 200px; border-radius: 8px !important;">
          </div>
          <div class="d-flex flex-column ms-1">
            <label for="status">Local de estágio:</label>
            <input name="motivo"  type="text" class="form-control" style=" border-radius: 8px !important;">
          </div>                                                                                  
          <div class="d-flex ms-1">
            <div class="d-flex flex-column">
              <label for="status">Data de solicitação:</label>
              <div class="d-flex">
                <input type="date" name="dt_solicitacao1" class="form-control" id="" style="border-radius: 8px !important;">
                <input type="date" name="dt_solicitacao2" class="form-control ms-1" id="" style="border-radius: 8px !important;">
              </div>
            </div>                                                             
            <button type="submit" class="btn btn-dark ms-2 mt-auto">
              <i class="fa-solid fa-magnifying-glass"></i>
            </button>
        </div>        
        </div>
      </form>
    </div>
  </div>
<div class="row mx-auto">
    <div class="col p-2 d-flex justify-content-center align-items-center">
        <table class="table">
            <thead>
                <tr>
                    <th></th>
                    <th class="pe-5">Status</th>
                    <th class="pe-5">Nome do Aluno</th> 
                    <th>Universidade</th>
                    <th class="pe-5">Curso</th>
                    <th class="pe-5">Local de Estágio</th>
                    {% if supervisor %}
                    <th class="pe-5">Supervisor</th>
                    <th class="pe-5">Secretária</th>
                    {% endif %}
                    <th class="pe-5">Data de Solicitação</th>
                    <th class="pe-5">Processo</th>
                </tr>
            </thead>
            <tbody>
                {% for i in estudante %}
                <tr>
                    <td class="pe-4 text-success">{% if i.TCE %}<i class="fa-solid fa-file-pdf"></i>{% endif %}</td>
                    <td class="pe-5">{{i.get_status_display}}</td>
                    <td class="pe-5">{{i.estudante.pessoa.nome}}</td>
                    <td>{{i.universidade.nome}}</td>
                    <td class="pe-5">{{i.estudante.curso.nome}}</td>
                    <td class="pe-5">{% if i.local_do_estagio %}<i class="fa-solid fa-magnifying-glass me-2"></i>{{i.local_do_estagio.local}}{% else %}<i class="fa-solid fa-magnifying-glass me-2"></i>{{i.local_do_estagio_de_pretensao.local}}{% endif %}</td>
                    {% if supervisor %}                    
                    <td class="pe-5">{{i.supervisor.nome}}</td>
                    <td class="pe-5">{{i.supervisor.secretaria.nome}}</td>
                    {% endif %}
                    <td class="pe-5">{{i.data_inclusao}}</td>
                    <td class="pe-5 text-center"><a href="{% url 'estagio:adm_processo_da_vaga' i.id %}?next=/estagio/candidato">
                        <i class="fa-solid fa-eye me-2"></i>Visualizar 
                    </a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<script>
    let openfiltros = false
    function showFiltros(){
    if (openfiltros){      
      document.getElementById('filtros').style.display='none'
      openfiltros=false
    }else{
      document.getElementById('filtros').style.display='flex'
      openfiltros=true
    }
  }
</script>
{% endblock %}
{% block footer %}
{% include 'desenvolve_nf/instagram.html' %}
{% endblock %}

estagio/templates/estagio/listar_vagas.html
{% extends 'template.html' %}
{% load static %}
{% block nav %}
{% include 'nav_estagio.html' %}
{% endblock %}
{% block css %} {% endblock %}
{% block main %}
<div class="row">
  <div class="col d-flex">       
      <div class="m-auto py-0 w-100">           
        <div class="cursos-text mx-2 d-flex w-100">
          <h2 class="my-auto">Vagas</h2>                        
          <a href="{% url 'estagio:cadastrar_vagas' %}" class="ms-auto mt-2 btn btn-primary mb-2"><i class="fa-solid fa-clipboard me-2"></i>Cadastrar vaga</a>
          <a href="{% url 'estagio:adm' %}" class="ms-1 mt-2 me-3 btn btn-primary mb-2"><i class="fa-solid fa-backward-step me-2"></i>Voltar</a>              
        </div>            
    </div>
  </div>
</div>


    <div class="row">
      <div class="col d-flex flex-wrap">
        {% for vaga in  vagas %}
        <div class="item mx-auto mb-4">
          <div class="c-img" style="position: relative;">
            <img class="img-fluid" style="border-radius: 10px;" src="{{vaga.img.url}}" alt="">
          </div>
        <div class="cursos-text mx-2 d-flex flex-column">
            <h5 class="mb-3">{{vaga.nome}}</h5>
            <a href="{% url 'estagio:editar_vagas' vaga.id %}" class="py-1 mt-auto text-center">
              Editar
            </a>
          </div>
      </div>
        {% endfor %}
      </div>
    </div>

{% endblock %}
{% block footer %}
{% include 'desenvolve_nf/instagram.html' %}
{% endblock %}